<?php

return [
    'name' => 'Sayurin',
    'tagline' => 'Web Application',
    'description' => 'A powerful web application built with Laravel.',
    'alamat' => 'jalan tanah koja RT. 01/02 No,. 45',
    'telepon' => '0853454354353',
    'email' => 'itok.toni@gmail.com',
    'logo' => '/favicon.svg',
    'favicon' => '/favicon.ico',
    'colors' => [
        'primary' => '#388e3c',
        'on_primary' => '#ffffff',
        'primary_container' => '#1e40af',
        'on_primary_container' => '#a8b8ff',
        'primary_fixed' => '#dde1ff',
        'primary_fixed_dim' => '#b8c4ff',
        'surface' => '#f7f9fb',
        'surface_container' => '#eceef0',
    ],
    'social' => [
        'facebook' => '',
        'instagram' => '',
        'twitter' => '',
        'youtube' => '',
        'tiktok' => '',
    ],
    'footer_text' => 'footer text',
    'warehouse_name' => 'Gudang Pusat',
    'warehouse_address' => 'Jl. Raya Pasuruan No. 1, Pasuruan',
    'warehouse_lat' => '-7.644872',
    'warehouse_lng' => '112.904528',
    'updated_at' => '2026-08-24T06:43:23+00:00',
    'created_at' => '2026-08-23T06:24:40+00:00',
    'id' => 1,
];
